### ISSUE TITLE
Unable to start tomcat with jul-jsonformatter and json-simple

### ISSUE THREAD

**Issue by Z01ndels** [devatherock/jul-jsonformatter#13]
I'm trying to use your pretty simple json formatter for JUL in Tomcat. I more or less followed the recipe given in [Integrating Logstash with Tomcat 7](https://paluch.biz/blog/105-integrating-logstash-with-tomcat-7.html) and replaced their jars with juli-jsonformatter and json-simple. Unfortunatly, tomcat startup fails with the following message

```
Handler error                                                                                                                                                
java.lang.reflect.InvocationTargetException                                                                                                                  
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)                                                                             
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)                                                      
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)                                              
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)                                                                                   
        at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:589)                                                           
        at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:525)                                                           
        at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:327)                                                           
        at java.util.logging.LogManager$3.run(LogManager.java:399)                                                                                           
        at java.util.logging.LogManager$3.run(LogManager.java:396)                                                                                           
        at java.security.AccessController.doPrivileged(Native Method)                                                                                        
        at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:396)                                                                     
        at java.util.logging.LogManager.access$800(LogManager.java:145)                                                                                      
        at java.util.logging.LogManager$2.run(LogManager.java:345)                                                                                           
        at java.security.AccessController.doPrivileged(Native Method)                                                                                        
        at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)                                                                     
        at java.util.logging.LogManager.getLogManager(LogManager.java:378)                                                                                   
        at java.util.logging.Logger.demandLogger(Logger.java:448)                                                                                            
        at java.util.logging.Logger.getLogger(Logger.java:502)                                                                                               
        at org.apache.juli.logging.DirectJDKLog.<init>(DirectJDKLog.java:61)                                                                                 
        at org.apache.juli.logging.DirectJDKLog.getInstance(DirectJDKLog.java:181)                                                                           
        at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:133)                                                                               
        at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:156)                                                                               
        at org.apache.juli.logging.LogFactory.getLog(LogFactory.java:211)                                                                                    
        at org.apache.catalina.startup.Bootstrap.<clinit>(Bootstrap.java:50)                                                                                 
Caused by: java.lang.ExceptionInInitializerError                                                                                                             
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)                                                                             
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)                                                      
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)                                              
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)                                                                                   
        at java.lang.Class.newInstance(Class.java:442)                                                                                                       
        at java.util.logging.LogManager.getFormatterProperty(LogManager.java:1551)                                                                           
        at java.util.logging.StreamHandler.configure(StreamHandler.java:89)                                                                                  
        at java.util.logging.StreamHandler.<init>(StreamHandler.java:107)                                                                                    
        at java.util.logging.ConsoleHandler.<init>(ConsoleHandler.java:98)                                                                                   
        ... 24 more                                                                                                                                          
Caused by: java.lang.NullPointerException                                                                                                                    
        at java.util.logging.Logger.doSetParent(Logger.java:2069)                                                                                            
        at java.util.logging.Logger.getAnonymousLogger(Logger.java:644)                                                                                      
        at java.util.logging.Logger.getAnonymousLogger(Logger.java:603)                                                                                      
        at io.github.devatherock.json.formatter.JSONFormatter.createJsonConverter(JSONFormatter.java:190)                                                    
        at io.github.devatherock.json.formatter.JSONFormatter.<clinit>(JSONFormatter.java:45)                                                                
        ... 33 more                                                                                                                                          
```

As I have changed my ConsoleLogger formatter this way

```
java.util.logging.ConsoleHandler.level = ALL
java.util.logging.ConsoleHandler.formatter=io.github.devatherock.json.formatter.JSONFormatter
```

What I understand is that jul-jsonformatter is loaded, then the `JSONFormatter#getConverter()` method is invoked. It tries to laod Jackson (and fails). It then tries to load json-simple and ... fails. And this is the weird part. Because json-simple is correctly set in my CLASSPATH.

Have you got any idea of something I could do to fix that ?

**Comment by Z01ndels** [comment]
My bad, my config was incorrect, and Tomcat is full of dragons
